### PR TITLE
astro ec-config loader should handle Bun resolver messages at startup

### PR DESCRIPTION
**Pull request by tylergannon**
Bun users of astro-expressive-code get the following error during application startup:

```
> [6/6] RUN bun run build:                                                                                                                         
0.113 $ astro build                                                                                                                                 
0.963 msg.match is not a function. (In 'msg.match(/ec\.config\.mjs.*(imported from|resolved id)/)', 'msg.match' is undefined)                       
0.963   Stack trace:
0.963     at <anonymous> (/sudovanilla/node_modules/astro-expressive-code/dist/index.js:39:10)
0.971 error: script "build" exited with code 1
```

The startup process for astro-expressive-code is to attempt to load each of the possible locations for the config file.  Normal module-not-found errors get passed up.  

On Bun, this process is hanging up because the Bun team decided to throw `ResolveMessage` instead of `Error`, so the type comparison was failing on Bun.

With this change, instead of finding the error message and code implicitly through type checking, I've just explicitly checked to see if the error object has got a `message` attribute.

### CODE REVIEW

**Comment by tylergannon** [comment]
It looks great!  Though, I probably should have thought to wonder whether there might be other places in this repo, where the code similarly expects the module resolver to throw `Error` for MODULE_NOT_FOUND.

But it _should_ be fine.  Bun is intended as a drop-in replacement for Node.  For the vast majority of functionality, that is the case.

Screenshot 2024-04-03 at 7 02 23 AM

**Comment by tylergannon** [comment]
BTW Thanks for your great work building / maintaining this tool for the community!  🎆

**Review by hippotastic — APPROVED** [review]
I just installed Bun and ran some checks. Your fix does work, thank you very much!

I'll merge this and then follow up with some minor tweaks to make the error message pattern detection more robust. Bun uses a slightly different error message and I need to differentiate between ec.config.mjs itself not being found (which should be ignored) and a module imported by ec.config.mjs not being found (which should still throw).

During my testing in Bun, I also found some other issues that require minimal changes (like adding the `type` modifier to an import/export to make it work with Bun). I'll fix these as well in a follow-up PR.

Thanks again!

**Comment by hippotastic** [comment]
I just released this with Expressive Code v0.34.0. Thanks again!

I'll create a Starlight PR to bump the EC version there as well. The next Starlight release will probably be on Friday.

**Pull request merged**
