### PR TITLE
Improve performance of  `tabindex` module

### PR DESCRIPTION
**Pull request by delucis**
This PR aims to improve performance of the script which applies/removes `tabindex` attributes to code blocks depending on whether or not they are scrollable.

While looking into some performance details on lower-powered devices, I realised that because this script reads element dimensions (`scrollWidth` and `clientWidth`), it could cause forced style recalculation/layout work if running while this information is not yet fully resolved (for example during initial page load).

This PR wraps the tab index update logic in a `requestIdleCallback()`, to defer setting `tabindex` to a moment when the main thread is idle. In general this means that any required style/layout work the browser has planned will be complete before Expressive Code tries to measure anything.

I also removed the initial call to `updateTabIndex()` made at the same time as adding an element to the resize observer. In my testing, `ResizeObserver` already fires its callback immediately for every newly observed element, so manually calling `updateTabIndex()` was redundant.

I tested this alongside another change in https://github.com/withastro/starlight/pull/2155 which allowed the `DOMContentLoaded` event to fire quite a bit earlier on a throttled CPU.

### CODE REVIEW

**Comment by hippotastic** [comment]
Thank you for this PR!

If I remember correctly, one of the reasons why I used `setTimeout` with the value 250 in my original code was that horizontally resizing a browser window containing a page with many code snippets felt sluggish without a reasonable debounce timeout value. Have you checked the subjective performance of your new code vs. the original code in such a scenario? I'm curious to see if `window.requestIdleCallback` also satisfies this and does not get called too often to slow resizing down.

**Comment by delucis** [comment]
> Have you checked the subjective performance of your new code vs. the original code in such a scenario?

Good question. No, I didn’t think to test that — I will. We actually have similar logic for resizes for something in Starlight where I ended up with `setTimeout(() => requestIdleCallback(...), 200)`, so it could be still needed. Let me confirm.

**Comment by delucis** [comment]
Did some testing, and it does look like with _**only**_ the `requestIdleCallback`, the resize logic can run a bit too often, so I have reintroduced the `setTimeout` as well.

I also noticed that running tests updates the minified version which appears to be committed to the repo so I’ve included that update too. Is that correct?

**Comment by delucis** [comment]
Hmm, hold on, just tested this in https://github.com/withastro/starlight/pull/2155 and seeing the old behaviour again. I think I’ll need to investigate a bit further.

**Comment by delucis** [comment]
Ah yeah, seems to be something to do with Netlify’s caching of the `ec.js` in between builds. Testing locally, I can confirm this is looking good 👍

**Comment by delucis** [comment]
@hippotastic Do you need anything else from me here? I think this PR should be good to go!

**Comment by hippotastic** [comment]
No, I also think it's fine! Thank you :)

**Comment by hippotastic** [comment]
I've just released your fix as v0.35.4. Thanks again!

**Pull request merged**
