### PR TITLE
Add support for Astro v3 beta

### LINKED ISSUE #42: Astro v3 support
Update `package.json` in astro-integration to accept Astro v3 (currently beta) without warning.
No issues experienced yet.

```
 WARN  Issues with peer dependencies found
.
└─┬ astro-expressive-code 0.19.1
  └── ✕ unmet peer astro@^2: found 3.0.0-beta.0
```

### PR DESCRIPTION
**Pull request by fflaten**
Allows Astro v3 incl. preview versions as peer dependency.

Fix #42

### CODE REVIEW

**Comment by hippotastic** [comment]
Thank you for this PR! I noticed that your `pnpm-lock.yaml` contained changes unrelated to the PR, so I updated the lockfile to only include the required change.

**Comment by fflaten** [comment]
Yeah, not sure why (outdated lockfile?) or how I could trigger it only for my change.

**Comment by hippotastic** [comment]
I just published your changes to NPM as version 0.19.2. Thanks again!

**Comment by fflaten** [comment]
Thank you :)

**Pull request merged**
